### ISSUE TITLE
https://github.com/xmm7360/xmm7360-pci/issues/96 is fixed

### ISSUE THREAD

**Issue by tgxn** [wafflepie/dotfiles#11]
https://github.com/wafflepie/dotfiles/blob/master/devices/waffle-x13y/fuck-dsl.sh#L10

https://github.com/xmm7360/xmm7360-pci/issues/96 is closed by https://github.com/xmm7360/xmm7360-pci/pull/117 now <3

**Comment by wafflepie** [comment]
Awesome stuff, thanks a lot! Ugly `sed` removed.
